# General properties
nameNode=hdfs://namenode:9000
jobTracker=localhost:8032
# user.name=your-username
oozie.use.system.libpath=true
queueName=default
oozieRoot=oozie
userName=${user.name}

homeFolder=${nameNode}/user/${userName}/${oozieRoot}

my_concurrency=2
my_timeout=60

# Hive credentials
hiveUsername=hive
hivePassword=hive

start=2024-09-012T00:00Z
end=2024-10-13T00:00Z
oozie.bundle.application.path=${homeFolder}/bundles


# Full historical home
# Custom properties for shell scripts
scriptsHome=${homeFolder}/scripts
start_historical_load_script=${scriptsHome}/start_historical_load.sh
ingest_operational_data_script=${scriptsHome}/ingest_operational_data.sh
finish_historical_load_script=${scriptsHome}/finish_historical_load.sh

# Custom properties for Hive scripts
hiveHome=${homeFolder}/scripts/hive
load_audit_hive=${hiveHome}/load_audit_hive.hql
create_staging_schema_hive=${hiveHome}/create_staging_schema_hive.hql
create_master_schema_hive=${hiveHome}/create_master_schema_hive.hql

# Custom properties for Hive transformation scripts
hiveTransformationHome=${hiveHome}/hive_transformations
load_master_tradetype_hive=${hiveTransformationHome}/1_load_master_tradetype.hql
load_master_statustype_hive=${hiveTransformationHome}/2_load_master_statustype.hql
load_master_taxrate_hive=${hiveTransformationHome}/3_load_master_taxrate.hql
load_master_industry_hive=${hiveTransformationHome}/4_load_master_industry.hql
transform_load_master_dimdate_hive=${hiveTransformationHome}/5_transform_load_master_dimdate.hql
transform_load_master_dimtime_hive=${hiveTransformationHome}/6_transform_load_master_dimtime.hql
transform_load_master_dimcompany_hive=${hiveTransformationHome}/7_transform_load_master_dimcompany.hql
load_master_dimessages_dimcompany_hive=${hiveTransformationHome}/8_load_master_dimessages_dimcompany.hql
transform_load_master_dimbroker_hive=${hiveTransformationHome}/9_transform_load_master_dimbroker.hql
transform_load_master_prospect_hive=${hiveTransformationHome}/10_transform_load_master_prospect.hql
transform_load_master_dimcustomer_hive=${hiveTransformationHome}/11_transform_load_master_dimcustomer.hql
load_master_dimessages_dimcustomer_hive=${hiveTransformationHome}/12_load_master_dimessages_dimcustomer.hql
update_master_prospect_hive=${hiveTransformationHome}/13_update_master_prospect.hql
transform_load_master_dimaccount_hive=${hiveTransformationHome}/14_transform_load_master_dimaccount.hql
transform_load_master_dimsecurity_hive=${hiveTransformationHome}/15_transform_load_master_dimsecurity.hql
transform_load_master_dimtrade_hive=${hiveTransformationHome}/16_transform_load_master_dimtrade.hql
load_master_dimessages_dimtrade_hive=${hiveTransformationHome}/17_load_master_dimessages_dimtrade.hql
transform_load_master_financial_hive=${hiveTransformationHome}/18_transform_load_master_financial.hql
transform_load_master_factcashbalances_hive=${hiveTransformationHome}/19_transform_load_master_factcashbalances.hql
transform_load_master_factholdings_hive=${hiveTransformationHome}/20_transform_load_master_factholdings.hql
transform_load_master_factwatches_hive=${hiveTransformationHome}/21_transform_load_master_factwatches.hql
transform_load_master_factmarkethistory_hive=${hiveTransformationHome}/22_transform_load_master_factmarkethistory.hql
load_master_dimessages_factmarkethistory_hive=${hiveTransformationHome}/23_load_master_dimessages_factmarkethistory.hql


# Incremental update home
incrementalUpdateHome=${hiveHome}/hive_incremental_update